-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgY4s0PNs8CaCXhr05
RgrvBaaY1VFuha3SwqIm+x4NBL2gCgYIKoZIzj0DAQehRANCAATu4Rm8DWUfH5vK
LfmppNcda82KeX66pTkmed3geoQupnwOpGbgVy/6Jz7gU+iLBhyRBCe4FqEWRknr
vBNN+tgN
-----END PRIVATE KEY-----